runtime: python37
entrypoint: gunicorn -b :$PORT main:app
includes:
  - env_variables.yaml
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20
# automatic_scaling:
#   max_instances: 1
